[package]
name = "Kasane-Logic"
version = "0.0.1"
edition = "2024"
license = "MIT"


[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = "1.0.141"
schemars = "1.0.4"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name="id_new"
harness = false

[features]
default = []
serde_support = ["serde"]