[package]
name = "logic"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = "1.0.141"
schemars = "1.0.4"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name="id_new"
harness = false

[features]
default = []
serde_support = ["serde"]