name: Memori Benchmark

on:
  push:
    branches:
      - main

jobs:
  memori:
    uses: Tomoro0726/Memori/.github/workflows/memori-publish.yml@master
    with:
      pages_branch: "memori"
