name: Criterion Benchmark

on:
  push:
    branches: [main]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Criterion data
        uses: actions/cache@v4
        with:
          path: target/criterion
          key: criterion-${{ github.run_id }}
          restore-keys: |
            criterion-

      - name: Run benchmark
        run: cargo bench --benches -- --output-format bencher > benchmark_result.txt

      - name: Store continuous benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: benchmark_result.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: "dev/bench"
          comment-on-alert: true
          fail-on-alert: false

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Copy and Push HTML Report
        run: |
          # 過去の不完全なreportフォルダが残っていれば削除
          rm -rf gh-pages-dir/report

          # 古い全体のデータを削除し、今回生成されたディレクトリ全体をコピー
          rm -rf gh-pages-dir/criterion
          cp -r target/criterion gh-pages-dir/criterion

          # gh-pages ブランチに Push
          cd gh-pages-dir
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # フォルダごとGitに追加
          git add criterion/

          # 変更がない場合はエラーで止まらないように '|| exit 0' をつける
          git commit -m "Update full Criterion HTML report" || exit 0
          git push
